#!/usr/bin/env bash

OUTFILE="charlesOke.txt"
echo -e "\n=========Q2.2=========\n" > "$OUTFILE"
echo -e "---Current Date and Time---">>"$OUTFILE"
date >> "$OUTFILE"
echo "" >> "$OUTFILE"
echo -e "---Hostname---" >>"$OUTFILE"
hostname >>"$OUTFILE"
echo "" >> "$OUTFILE"
echo -e "---Architecture---" >>"$OUTFILE"
arch >> "$OUTFILE"
echo "" >> "$OUTFILE"
echo -e "---System Information---" >> "$OUTFILE"
uname -a>> "$OUTFILE"
echo "" >> "$OUTFILE"
echo -e "---Uptime---" >> "$OUTFILE"
uptime >> "$OUTFILE"
echo "" >> "$OUTFILE"
echo -e "---Current User---" >> "$OUTFILE"
whoami >> "$OUTFILE"
echo "" >> "$OUTFILE"
echo -e "---Logged in Users---" >> "$OUTFILE"
who >> "$OUTFILE"
echo "" >> "$OUTFILE"
echo -e "---Who is doing what---" >> "$OUTFILE"
w >> "$OUTFILE"
echo "" >> "$OUTFILE"
echo -e "---Top processes snap---" >> "$OUTFILE"
top -b -n 1 | head -n 15 >> "$OUTFILE"
echo "" >> "$OUTFILE"
echo -e "---History Command---" >> "$OUTFILE"
cat ~/.bash_history >> "$OUTFILE"
